#!/usr/bin/env python3
"""Generates the MonoGame content pipeline entries for the extracted sprites.

Reads src/Robotron2084/Content/Sprites/*.png and Content/Effects/*.fx and
emits:
  1. src/Robotron2084/Content/Content.mgcb  (font entry + effect entries +
     one PNG entry per file)
  2. src/Robotron2084/Rendering/SpriteContentPaths.cs (static content-path table)

Re-run whenever new sprite PNGs are added to Content/Sprites/.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPRITES_DIR = ROOT / "src/Robotron2084/Content/Sprites"
EFFECTS_DIR = ROOT / "src/Robotron2084/Content/Effects"
MGCB = ROOT / "src/Robotron2084/Content/Content.mgcb"
PATHS_CS = ROOT / "src/Robotron2084/Rendering/SpriteContentPaths.cs"

def main() -> int:
    pngs = sorted(p.stem for p in SPRITES_DIR.glob("*.png"))
    if not pngs:
        print(f"no PNGs found in {SPRITES_DIR}", file=sys.stderr)
        return 1

    # ---- Content.mgcb ----
    lines = [
        "#----------------------------- Global Properties ----------------------------#",
        "",
        "/outputDir:bin/$(Platform)/Content",
        "/intermediateDir:obj/$(Platform)/Content",
        "/platform:DesktopGL",
        "/config:",
        "/profile:Reach",
        "/compress:False",
        "",
        "#-------------------------------- References ---------------------------------#",
        "",
        "#---------------------------------- Content -----------------------------------#",
        "",
        "#begin Fonts/Default.spritefont",
        "/importer:FontDescriptionImporter",
        "/processor:FontDescriptionProcessor",
        "/processorParam:PremultiplyAlpha=True",
        "/processorParam:TextureFormat=Compressed",
        "/build:Fonts/Default.spritefont",
    ]
    for fx in sorted(EFFECTS_DIR.glob("*.fx"), key=lambda p: p.name):
        lines += [
            f"#begin Effects/{fx.name}",
            "/importer:EffectImporter",
            "/processor:EffectProcessor",
            f"/build:Effects/{fx.name}",
            "",
        ]
    for name in pngs:
        lines += [
            f"#begin Sprites/{name}.png",
            "/importer:TextureImporter",
            "/processor:TextureProcessor",
            "/processorParam:ColorKeyColor=255,0,255,255",
            "/processorParam:ColorKeyEnabled=True",
            "/processorParam:GenerateMipmaps=False",
            "/processorParam:PremultiplyAlpha=True",
            "/processorParam:ResizeToPowerOfTwo=False",
            "/processorParam:MakeSquare=False",
            "/processorParam:TextureFormat=Color",
            f"/build:Sprites/{name}.png",
            "",
        ]
    MGCB.write_text("\n".join(lines), encoding="ascii", newline="\n")

    # ---- SpriteContentPaths.cs ----
    entries = ",\n".join(f'        "Sprites/{n}"' for n in pngs)
    paths_cs = f"""namespace Robotron2084.Rendering;

/// <summary>
/// Every extracted sprite content path (one per PNG in
/// <c>Content/Sprites/</c>). GENERATED by tools/generate-mgcb.py — re-run it
/// when sprites are added; do not edit by hand.
/// </summary>
public static class SpriteContentPaths
{{
    public static readonly string[] All =
    [
{entries},
    ];
}}
"""
    PATHS_CS.write_text(paths_cs, encoding="utf-8", newline="\n")

    print(f"{len(pngs)} sprites -> {MGCB.name} + {PATHS_CS.name}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
